/* Romus · Guía metodológica (método Kuetz) — ayuda y modo tutorial.
   © 2026 Brian Gonzalo Suárez Acevedo. Texto ORIGINAL escrito para Romus.
   Lecturas recomendadas para profundizar (se citan en cada tema, como exige la ética académica):
   - Hernández Sampieri, R., Fernández Collado, C. y Baptista Lucio, M. P. (2014). Metodología de la investigación (6.ª ed.). McGraw-Hill. [HS]
   - Martínez Miguélez, M. (2004). Epistemología y metodología cualitativa en las ciencias sociales. Trillas, cap. 3. [MM]
   No reproduce texto de las obras: explica sus ideas con palabras propias e indica dónde ampliarlas. */
window.Guia = (function () {
  const HS = "Hernández Sampieri et al. (2014)";
  const MM = "Martínez Miguélez (2004)";

  /* Cada tema: id, cat, titulo, claves (palabras para encontrarlo), resumen, puntos, ejemplo, error, fuente, accion (opcional: comando de Romus). */
  const TEMAS = [
    /* ---------- Fundamentos ---------- */
    { id: "investigacion", cat: "Fundamentos", titulo: "¿Qué es investigar?",
      claves: ["investigacion", "investigar", "que es investigar", "proceso de investigacion"],
      resumen: "Investigar es aplicar un conjunto de procesos sistemáticos, críticos y empíricos para estudiar un fenómeno o problema. No es solo buscar información: es producir conocimiento con un método que otros puedan revisar.",
      puntos: ["Sistemático: sigue pasos ordenados y explícitos.", "Crítico: se evalúa y se mejora constantemente.", "Empírico: se apoya en datos o en la experiencia del fenómeno.", "Hay tres grandes rutas: cuantitativa, cualitativa y mixta."],
      ejemplo: "Preguntarse por qué hay conflictos en el recreo y diseñar cómo estudiarlo con datos es investigar; leer opiniones en internet sobre el tema, no.",
      error: "Confundir una revisión bibliográfica o un ensayo de opinión con una investigación.",
      fuente: HS + ", cap. 1" },
    { id: "enfoques", cat: "Fundamentos", titulo: "Enfoques: cuantitativo, cualitativo, mixto y teórico",
      claves: ["enfoque", "enfoques", "ruta", "rutas", "cuantitativo", "cualitativo", "mixto", "diferencia entre cuantitativo y cualitativo", "paradigma"],
      resumen: "El enfoque cuantitativo mide, prueba hipótesis y generaliza con estadística; es secuencial. El cualitativo comprende significados desde la perspectiva de los participantes; es inductivo, flexible y en espiral. El mixto combina ambos para obtener una visión más completa.",
      puntos: ["Cuantitativo: variables, medición, muestras representativas, análisis estadístico.", "Cualitativo: categorías, datos en palabras o imágenes, muestras intencionales, interpretación.", "Mixto: integra datos de ambos tipos y produce metainferencias.", "Teórico-documental: trabaja con textos y argumentos, no con datos de campo (filosofía, epistemología, teoría).", "Ningún enfoque es «mejor»: se elige según la pregunta."],
      ejemplo: "¿Cuánto mejora la convivencia con un programa de juegos? → cuantitativo. ¿Cómo viven los estudiantes el conflicto en el recreo? → cualitativo.",
      error: "Elegir el enfoque antes de tener clara la pregunta, o mezclar lenguaje de ambos (por ejemplo, «hipótesis» y «saturación» sin justificar un diseño mixto).",
      fuente: HS + ", cap. 1", accion: "enfoque" },
    { id: "idea", cat: "Fundamentos", titulo: "De la idea al tema de investigación",
      claves: ["idea", "ideas", "tema", "elegir tema", "como elegir un tema", "origen de la investigacion", "fuentes de ideas"],
      resumen: "Las investigaciones nacen de ideas que suelen ser vagas al principio: experiencias, lecturas, conversaciones, observaciones o problemas del trabajo. Para volverlas investigables hay que conocer los antecedentes y acotarlas.",
      puntos: ["Revisa qué se ha estudiado antes sobre la idea.", "Busca un ángulo novedoso o un contexto no estudiado.", "Una buena idea es interesante para ti, aporta algo nuevo y ayuda a resolver un problema o a construir teoría.", "Acota: quién, dónde, cuándo y qué aspecto."],
      ejemplo: "Idea vaga: «el deporte y los jóvenes». Acotada: «efecto del entrenamiento funcional en la condición física de estudiantes de 10.º de un colegio público de Floridablanca».",
      error: "Quedarse con un tema tan amplio que no cabe en un proyecto.",
      fuente: HS + ", cap. 2", accion: "idear" },
    { id: "epistemologia", cat: "Fundamentos", titulo: "Epistemología y paradigma",
      claves: ["epistemologia", "epistemologico", "posicionamiento epistemologico", "paradigma", "paradigmas", "ontologia", "sistemico", "positivismo", "interpretativo"],
      resumen: "Todo método está inserto en un paradigma, y el paradigma en una visión del mundo. La observación nunca es neutral: depende de la teoría y del punto de vista de quien investiga. Por eso conviene declarar desde dónde se investiga.",
      puntos: ["Declara tu paradigma: positivista, interpretativo, crítico, sistémico o complejo.", "Explica por qué ese paradigma es coherente con tu pregunta y tu método.", "Un paradigma sistémico y dialéctico que integra lo empírico, lo interpretativo y lo crítico.", "La cientificidad exige rigor, sistematicidad y criticidad, junto con apertura y creatividad."],
      ejemplo: "«Esta investigación se sitúa en el paradigma interpretativo, porque busca comprender los significados que los docentes atribuyen a la evaluación».",
      error: "Nombrar un paradigma sin que el método sea coherente con él.",
      fuente: MM + ", cap. 3" },
    { id: "cientificidad", cat: "Fundamentos", titulo: "¿Qué hace científico un estudio?",
      claves: ["cientificidad", "rigor cientifico", "ciencia", "conocimiento cientifico", "criticidad", "sistematicidad"],
      resumen: "Lo científico no se reduce a medir: exige rigor, sistematicidad y criticidad. Implica superar una idea restrictiva de cientificidad que excluye la creatividad y el estudio de lo humano.",
      puntos: ["Rigor: procedimientos cuidadosos y justificados.", "Sistematicidad: un orden lógico explícito y verificable.", "Criticidad: someter las propias ideas a revisión.", "Apertura: admitir métodos adecuados a la naturaleza del objeto."],
      ejemplo: "Un estudio cualitativo es científico si documenta cómo recolectó y analizó los datos y somete sus interpretaciones a contraste.",
      error: "Creer que un estudio cualitativo es «menos científico» por no usar estadística.",
      fuente: MM + ", cap. 3" },

    /* ---------- Planteamiento ---------- */
    { id: "planteamiento", cat: "Planteamiento", titulo: "Planteamiento del problema",
      claves: ["planteamiento", "planteamiento del problema", "problema", "problema de investigacion", "plantear el problema", "descripcion del problema"],
      resumen: "Plantear el problema es afinar y estructurar la idea. En la ruta cuantitativa incluye objetivos, preguntas, justificación, viabilidad, deficiencias en el conocimiento y consecuencias del estudio. Debe expresar una relación entre conceptos o variables y poder estudiarse empíricamente.",
      puntos: ["Describe la situación con evidencia: qué pasa, a quién, dónde, desde cuándo.", "Delimita población, lugar y tiempo.", "Muestra qué no se sabe todavía (deficiencias en el conocimiento).", "Termina en la pregunta de investigación."],
      ejemplo: "«En la institución X, los registros de convivencia muestran 120 conflictos en el recreo durante 2025, concentrados en sexto grado…».",
      error: "Describir el tema en general sin evidencia del problema, o confundir el problema con su solución.",
      fuente: HS + ", cap. 3", accion: "coherencia" },
    { id: "objetivos", cat: "Planteamiento", titulo: "Objetivos de investigación",
      claves: ["objetivo", "objetivos", "objetivo general", "objetivos especificos", "verbos", "redactar objetivos", "como redactar objetivos"],
      resumen: "Los objetivos dicen qué pretende la investigación. Deben ser claros, alcanzables y congruentes entre sí. El general responde a la pregunta; los específicos son los pasos que, juntos, lo logran.",
      puntos: ["Empiezan con un verbo en infinitivo: describir, determinar, analizar, comparar, comprender, diseñar.", "Un solo objetivo general; tres o cuatro específicos.", "Cada específico debe poder rastrearse en la metodología.", "Evita verbos vagos como «conocer» o «entender» y acciones que no son de investigación (capacitar, implementar) si no las evaluarás."],
      ejemplo: "General: «Determinar el efecto de un programa de juegos cooperativos en la convivencia escolar de estudiantes de sexto grado». Específico: «Medir el nivel de convivencia antes y después del programa».",
      error: "Objetivos específicos que no suman al general, o un general que no responde la pregunta.",
      fuente: HS + ", cap. 3", accion: "coherencia" },
    { id: "preguntas", cat: "Planteamiento", titulo: "Preguntas de investigación",
      claves: ["pregunta", "preguntas", "pregunta de investigacion", "formular la pregunta", "como formular una pregunta"],
      resumen: "Las preguntas presentan el problema de forma directa. Deben ser claras, precisas y responderse con el estudio. Una buena pregunta dice qué se estudia, en quiénes y, si aplica, qué relación se busca.",
      puntos: ["Evita preguntas de sí o no y preguntas demasiado generales.", "Incluye los conceptos o variables centrales.", "Debe ser respondible con los recursos y el tiempo disponibles.", "En lo cualitativo, la pregunta es abierta y puede ajustarse en el campo."],
      ejemplo: "Débil: «¿El deporte es bueno?». Mejor: «¿Qué relación existe entre la actividad física semanal y el rendimiento académico en estudiantes de grado 10?».",
      error: "Hacer una pregunta que el diseño no puede responder (por ejemplo, preguntar por causas con un diseño descriptivo).",
      fuente: HS + ", cap. 3" },
    { id: "justificacion", cat: "Planteamiento", titulo: "Justificación",
      claves: ["justificacion", "justificar", "por que investigar", "relevancia", "conveniencia", "valor teorico", "utilidad metodologica", "implicaciones practicas"],
      resumen: "La justificación explica por qué vale la pena el estudio. Se argumenta con cinco criterios; no hace falta cumplirlos todos, pero cuantos más, mejor.",
      puntos: ["Conveniencia: ¿para qué sirve?", "Relevancia social: ¿quiénes se benefician y cómo?", "Implicaciones prácticas: ¿ayuda a resolver un problema real?", "Valor teórico: ¿llena un vacío o aporta a una teoría?", "Utilidad metodológica: ¿crea o mejora un instrumento o una forma de estudiar el fenómeno?"],
      ejemplo: "«Los resultados permitirán a la institución diseñar estrategias de convivencia basadas en evidencia (implicación práctica) y aportan un instrumento validado para medirla (utilidad metodológica)».",
      error: "Justificar solo con opiniones («es muy importante porque sí») o repetir el problema.",
      fuente: HS + ", cap. 3" },
    { id: "viabilidad", cat: "Planteamiento", titulo: "Viabilidad",
      claves: ["viabilidad", "factibilidad", "recursos", "es viable", "tiempo", "acceso"],
      resumen: "Un estudio es viable si se dispone de tiempo, recursos financieros, humanos y materiales, y del acceso al lugar y a los participantes. Conviene evaluarlo antes de comprometerse.",
      puntos: ["¿Tengo acceso a la población y permisos?", "¿El tiempo alcanza para recolectar y analizar?", "¿Cuento con los instrumentos y el software?", "¿Hay costos que no puedo cubrir?"],
      ejemplo: "Un experimento con 600 estudiantes en un semestre puede no ser viable para un trabajo de pregrado; una muestra de 60 en dos cursos sí.",
      error: "Plantear un alcance que no se puede ejecutar con los recursos reales.",
      fuente: HS + ", cap. 3" },
    { id: "planteamiento-cualitativo", cat: "Planteamiento", titulo: "Planteamiento cualitativo",
      claves: ["planteamiento cualitativo", "problema cualitativo", "proposito", "inmersion", "inmersion inicial", "ambiente", "campo"],
      resumen: "En la ruta cualitativa el planteamiento es abierto, expansivo y se va enfocando. Incluye propósito, preguntas, justificación, viabilidad y deficiencias en el conocimiento, además de una primera definición del ambiente o contexto. La inmersión inicial en el campo ayuda a afinarlo.",
      puntos: ["Plantea un propósito de comprensión, no una relación a probar.", "Las preguntas son generales y pueden cambiar.", "Las hipótesis no se prueban al inicio: emergen durante el estudio.", "Describe el ambiente y cómo entrarás al campo."],
      ejemplo: "Propósito: «Comprender cómo los estudiantes de sexto grado viven y significan los conflictos durante el recreo».",
      error: "Escribir un planteamiento cualitativo con lenguaje de variables y medición.",
      fuente: HS + ", cap. 12" },

    /* ---------- Marco teórico ---------- */
    { id: "marco-teorico", cat: "Marco teórico", titulo: "Marco teórico (perspectiva teórica)",
      claves: ["marco teorico", "perspectiva teorica", "teoria", "teorias", "como hacer el marco teorico", "marco referencial"],
      resumen: "El marco teórico sustenta el estudio con teorías, investigaciones previas y antecedentes. Sirve para prevenir errores, orientar el método, ampliar el horizonte, sugerir hipótesis y servir de referencia para interpretar los resultados.",
      puntos: ["Etapas: revisión analítica de la literatura y construcción del marco.", "Dos métodos para organizarlo: por mapeo (un mapa conceptual de la literatura) o por índices (un esquema de temas y subtemas).", "No es un collage de citas: debe hilar un argumento.", "Termina mostrando el vacío que tu estudio atiende."],
      ejemplo: "Índice: 1. Convivencia escolar (definiciones). 2. Juego cooperativo (teorías). 3. Estudios que relacionan ambos. 4. Vacío: pocos estudios en contextos rurales colombianos.",
      error: "Acumular definiciones de diccionario o copiar párrafos sin análisis.",
      fuente: HS + ", cap. 4", accion: "literatura" },
    { id: "revision-literatura", cat: "Marco teórico", titulo: "Revisión de la literatura",
      claves: ["revision de la literatura", "literatura", "antecedentes", "estado del arte", "fuentes", "buscar fuentes", "fuentes primarias", "fuentes secundarias"],
      resumen: "La revisión consiste en detectar, obtener y consultar la literatura útil, y extraer de ella lo relevante. Las fuentes primarias son los estudios originales; las secundarias y terciarias los resumen o los listan.",
      puntos: ["Prioriza artículos científicos recientes (últimos 5 a 10 años) y revisiones sistemáticas.", "De cada estudio extrae: autor, año, objetivo, método, muestra, hallazgo y limitaciones.", "Organiza por temas o tendencias, no estudio por estudio.", "Con Romus: «busca literatura sobre…» trae trabajos reales y los cita en APA 7."],
      ejemplo: "Una matriz de antecedentes con columnas Autor-año | Objetivo | Método | Hallazgo | Aporte a mi estudio.",
      error: "Citar solo fuentes secundarias (blogs, manuales) o trabajos muy antiguos sin justificación.",
      fuente: HS + ", cap. 4", accion: "literatura" },

    /* ---------- Ruta cuantitativa ---------- */
    { id: "alcance", cat: "Ruta cuantitativa", titulo: "Alcance: exploratorio, descriptivo, correlacional o explicativo",
      claves: ["alcance", "alcances", "exploratorio", "descriptivo", "correlacional", "explicativo", "tipo de investigacion", "nivel de investigacion"],
      resumen: "El alcance indica hasta dónde llega el estudio. Depende de cuánto se sabe del tema y de lo que se quiere lograr. Un mismo estudio puede combinar alcances.",
      puntos: ["Exploratorio: tema poco estudiado; abre camino.", "Descriptivo: especifica propiedades y características de un fenómeno o grupo.", "Correlacional: mide el grado de asociación entre dos o más variables (sin afirmar causa).", "Explicativo: busca las causas de los fenómenos; suele requerir diseño experimental.", "El alcance define el tipo de hipótesis y de diseño."],
      ejemplo: "«¿Se asocia el tiempo de pantalla con el rendimiento?» es correlacional; «¿El programa X mejora el rendimiento?» es explicativo.",
      error: "Afirmar causalidad a partir de una correlación (correlaciones espurias).",
      fuente: HS + ", cap. 5" },
    { id: "hipotesis", cat: "Ruta cuantitativa", titulo: "Hipótesis",
      claves: ["hipotesis", "hipotesis nula", "hipotesis alternativa", "tipos de hipotesis", "formular hipotesis", "prueba de hipotesis"],
      resumen: "Una hipótesis es una explicación tentativa del fenómeno, formulada como proposición que puede someterse a prueba. No todos los estudios cuantitativos las requieren: dependen del alcance (los exploratorios no las formulan).",
      puntos: ["Tipos de hipótesis de investigación: descriptivas de un dato, correlacionales, de diferencia de grupos y causales.", "Hipótesis nula (H0): niega la relación planteada.", "Hipótesis alternativa: otra posibilidad distinta a la de investigación y la nula.", "Debe referirse a una situación real, con variables comprensibles, relación clara y técnicas disponibles para probarla."],
      ejemplo: "Hi: «Los estudiantes que participan en el programa presentan mayor nivel de convivencia que los que no participan». H0: «No hay diferencia en el nivel de convivencia…».",
      error: "Formular hipótesis en un estudio exploratorio o cualitativo sin justificarlo, o hipótesis imposibles de medir.",
      fuente: HS + ", cap. 6" },
    { id: "variables", cat: "Ruta cuantitativa", titulo: "Variables: definición conceptual y operacional",
      claves: ["variable", "variables", "operacionalizacion", "operacionalizar", "definicion operacional", "definicion conceptual", "independiente", "dependiente", "dimensiones", "indicadores"],
      resumen: "Una variable es una propiedad que puede fluctuar y medirse u observarse. Cada variable necesita una definición conceptual (qué significa, según la teoría) y una definición operacional (cómo se medirá exactamente).",
      puntos: ["Independiente: la que se supone causa o se manipula.", "Dependiente: la que recibe el efecto y se mide.", "Operacionaliza en una tabla: variable → definición → dimensiones → indicadores → ítems → escala.", "El nivel de medición (nominal, ordinal, de intervalo o de razón) define el análisis estadístico."],
      ejemplo: "Convivencia escolar (conceptual: forma de relacionarse en la escuela basada en el respeto…). Operacional: puntaje en la escala X de 24 ítems tipo Likert, con dimensiones de respeto, cooperación y manejo de conflictos.",
      error: "Definir las variables solo con el diccionario o no decir con qué instrumento se medirán.",
      fuente: HS + ", cap. 6" },
    { id: "diseno-experimental", cat: "Ruta cuantitativa", titulo: "Diseños experimentales",
      claves: ["diseno experimental", "experimento", "experimental", "cuasiexperimental", "cuasiexperimento", "preexperimento", "grupo control", "preprueba", "posprueba", "pretest", "postest", "solomon", "factorial"],
      resumen: "En un experimento se manipula intencionalmente una o más variables independientes para analizar sus efectos sobre variables dependientes, con control de la situación. Hay preexperimentos, experimentos «puros» y cuasiexperimentos.",
      puntos: ["Requisitos: manipular la variable independiente, medir la dependiente y lograr control y validez interna.", "Experimento puro: grupos de comparación y asignación al azar (o emparejamiento).", "Cuasiexperimento: grupos ya formados (por ejemplo, cursos), sin asignación al azar.", "Preexperimento: un solo grupo, control mínimo; sirve como aproximación.", "Amenazas a la validez interna: historia, maduración, administración de pruebas, instrumentación, regresión, selección, mortalidad, entre otras."],
      ejemplo: "Dos cursos de sexto: uno recibe el programa (experimental) y otro no (control); ambos se miden antes y después. Es un cuasiexperimento con preprueba y posprueba.",
      error: "Llamar «experimental» a un estudio sin grupo de comparación ni manipulación.",
      fuente: HS + ", cap. 7" },
    { id: "diseno-no-experimental", cat: "Ruta cuantitativa", titulo: "Diseños no experimentales",
      claves: ["diseno no experimental", "no experimental", "transeccional", "transversal", "longitudinal", "panel", "cohorte", "tendencia", "encuesta"],
      resumen: "En los diseños no experimentales no se manipulan variables: se observan los fenómenos tal como ocurren. Pueden ser transeccionales (una sola medición) o longitudinales (varias mediciones en el tiempo).",
      puntos: ["Transeccionales: exploratorios, descriptivos o correlacionales-causales.", "Longitudinales: de tendencia, de evolución de grupo (cohortes) o panel (los mismos participantes).", "Útiles cuando no es ético o posible manipular la variable.", "Permiten describir y relacionar, pero la causalidad se afirma con cautela."],
      ejemplo: "Aplicar una encuesta de hábitos de actividad física a todos los estudiantes en octubre de 2026 es un diseño transeccional descriptivo.",
      error: "Concluir causas a partir de una sola medición transversal.",
      fuente: HS + ", cap. 7" },
    { id: "muestra", cat: "Ruta cuantitativa", titulo: "Población y muestra",
      claves: ["muestra", "muestreo", "poblacion", "tamano de muestra", "probabilistica", "no probabilistica", "aleatorio", "estratificado", "racimos", "conglomerados", "marco muestral", "calcular la muestra"],
      resumen: "La población es el conjunto de casos que concuerdan con ciertas especificaciones; la muestra es un subgrupo de ella. Primero se define la unidad de análisis (sobre qué o quiénes), luego la población y finalmente el tipo de muestra.",
      puntos: ["Probabilística: todos tienen la misma probabilidad de ser elegidos; permite generalizar (simple, estratificada, por racimos, sistemática).", "No probabilística: la elección depende del investigador; no permite generalizar estadísticamente.", "El tamaño de una muestra probabilística se calcula con el tamaño de la población, el nivel de confianza (p. ej., 95 %) y el margen de error (p. ej., 5 %).", "Describe el marco muestral: la lista de donde se eligen los casos."],
      ejemplo: "Población: 480 estudiantes de secundaria. Con 95 % de confianza y 5 % de error se necesitan unos 214; muestreo estratificado por grado.",
      error: "Llamar «aleatoria» a una muestra elegida por conveniencia.",
      fuente: HS + ", cap. 8" },
    { id: "instrumentos", cat: "Ruta cuantitativa", titulo: "Instrumentos: confiabilidad, validez y objetividad",
      claves: ["instrumento", "instrumentos", "confiabilidad", "validez", "validacion", "alfa de cronbach", "cronbach", "juicio de expertos", "validez de contenido", "validez de constructo", "validez de criterio", "objetividad", "cuestionario", "escala likert", "likert", "prueba piloto"],
      resumen: "Medir es vincular conceptos abstractos con indicadores empíricos. Todo instrumento debe ser confiable (resultados consistentes), válido (mide lo que dice medir) y objetivo (poco influido por quien lo aplica).",
      puntos: ["Confiabilidad: test-retest, formas alternativas, mitades partidas o consistencia interna (alfa de Cronbach; suele aceptarse desde 0,70).", "Validez de contenido: los ítems cubren todo el dominio (juicio de expertos).", "Validez de criterio: se compara con otra medida externa.", "Validez de constructo: el instrumento se comporta como predice la teoría (p. ej., análisis factorial).", "Haz una prueba piloto antes de aplicarlo."],
      ejemplo: "Escala de convivencia validada por cinco expertos (contenido), piloteada con 30 estudiantes (alfa = 0,86).",
      error: "Usar un cuestionario hecho por uno mismo sin ningún proceso de validación.",
      fuente: HS + ", cap. 9" },
    { id: "analisis-cuantitativo", cat: "Ruta cuantitativa", titulo: "Análisis de datos cuantitativos",
      claves: ["analisis cuantitativo", "analisis de datos", "estadistica", "estadistica descriptiva", "estadistica inferencial", "spss", "prueba t", "chi cuadrado", "correlacion de pearson", "pruebas parametricas", "no parametricas", "normalidad"],
      resumen: "El análisis sigue pasos: elegir el programa, explorar los datos, evaluar la confiabilidad y validez del instrumento, analizar descriptivamente cada variable y luego probar las hipótesis con estadística inferencial.",
      puntos: ["Descriptiva: frecuencias, media, mediana, moda y desviación estándar.", "Inferencial: pruebas paramétricas (t de Student, ANOVA, correlación de Pearson) si los datos cumplen supuestos como la normalidad.", "No paramétricas (chi cuadrado, U de Mann-Whitney, Spearman) si no los cumplen o el nivel de medición es nominal u ordinal.", "Reporta el nivel de significancia (p. ej., p < 0,05) y el tamaño del efecto."],
      ejemplo: "Para comparar la convivencia antes y después en el mismo grupo: prueba t para muestras relacionadas (o Wilcoxon si no hay normalidad).",
      error: "Elegir la prueba estadística sin considerar el nivel de medición ni la hipótesis.",
      fuente: HS + ", cap. 10" },
    { id: "reporte-cuantitativo", cat: "Ruta cuantitativa", titulo: "Reporte de resultados cuantitativo",
      claves: ["reporte", "informe final", "resultados", "discusion", "conclusiones", "reporte cuantitativo", "estructura del informe"],
      resumen: "Antes de escribir, define quién leerá el reporte y en qué contexto (académico o no académico). El reporte académico suele incluir portada, resumen, introducción, marco teórico, método, resultados, discusión, referencias y apéndices.",
      puntos: ["Resultados: presenta los datos sin interpretarlos (tablas y figuras numeradas).", "Discusión: interpreta, compara con la literatura, señala limitaciones y recomendaciones.", "Conclusiones: responden a la pregunta y a los objetivos.", "Usa normas como APA 7 para citas, tablas y referencias."],
      ejemplo: "Tabla 1. Puntajes de convivencia antes y después del programa (media y desviación estándar por grupo).",
      error: "Mezclar resultados con opiniones o presentar conclusiones que no se derivan de los datos.",
      fuente: HS + ", cap. 11" },

    /* ---------- Ruta cualitativa ---------- */
    { id: "muestreo-cualitativo", cat: "Ruta cualitativa", titulo: "Muestreo cualitativo y saturación",
      claves: ["muestreo cualitativo", "muestra cualitativa", "saturacion", "saturacion de categorias", "participantes", "muestra intencional", "bola de nieve", "informantes clave", "casos tipo", "expertos", "conveniencia", "maxima variacion"],
      resumen: "En lo cualitativo la muestra no busca representatividad estadística sino profundidad. Se eligen casos que ayuden a entender el fenómeno y el tamaño se decide en el campo hasta la saturación: cuando los nuevos casos ya no aportan información nueva.",
      puntos: ["Tipos: de máxima variación, homogénea, en cadena o bola de nieve, de casos extremos, teórica, de expertos, de casos tipo, por oportunidad o por conveniencia.", "Factores para el tamaño: capacidad operativa del investigador, entendimiento del fenómeno (saturación) y naturaleza del fenómeno.", "Primero hay una muestra inicial tras la inmersión; puede ajustarse.", "Justifica por qué esos participantes y no otros."],
      ejemplo: "Doce estudiantes de sexto elegidos por máxima variación (género, curso y nivel de participación en conflictos), hasta saturar las categorías.",
      error: "Calcular un tamaño de muestra estadístico para un estudio cualitativo.",
      fuente: HS + ", cap. 13" },
    { id: "recoleccion-cualitativa", cat: "Ruta cualitativa", titulo: "Recolección cualitativa: entrevistas, observación y grupos focales",
      claves: ["recoleccion cualitativa", "entrevista", "entrevistas", "entrevista semiestructurada", "observacion", "observacion participante", "grupo focal", "grupos focales", "diario de campo", "bitacora", "documentos", "historias de vida"],
      resumen: "En la ruta cualitativa el investigador es el principal instrumento. Recolecta datos en el ambiente natural de los participantes: observación, entrevistas, grupos de enfoque, documentos, materiales audiovisuales e historias de vida.",
      puntos: ["Entrevista: estructurada, semiestructurada o abierta; con guía flexible.", "Observación: no es mirar; implica estar atento a detalles, registrar y reflexionar.", "Grupos de enfoque: interacción de 3 a 10 personas sobre un tema.", "Lleva una bitácora o diario de campo con descripciones e interpretaciones separadas."],
      ejemplo: "Guía de entrevista semiestructurada con 8 preguntas abiertas sobre cómo viven los estudiantes el recreo, más observación de 6 recreos.",
      error: "Hacer entrevistas con preguntas cerradas de sí o no, como si fueran una encuesta.",
      fuente: HS + ", cap. 14" },
    { id: "analisis-cualitativo", cat: "Ruta cualitativa", titulo: "Análisis cualitativo: codificación y categorías",
      claves: ["analisis cualitativo", "codificacion", "codificar", "codificacion abierta", "codificacion axial", "codificacion selectiva", "categorias", "categorizacion", "temas", "unidades de analisis", "atlas ti", "nvivo", "memos"],
      resumen: "El análisis cualitativo no espera a tener todos los datos: recolección y análisis ocurren a la vez. Se organizan los datos, se definen unidades de análisis y se codifican en dos planos: primero se generan categorías y luego se relacionan entre sí en temas.",
      puntos: ["Prepara y transcribe los datos.", "Codificación en primer plano (abierta): asignar códigos a fragmentos y agruparlos en categorías.", "Codificación en segundo plano (axial o selectiva): relacionar categorías y generar temas o una teoría.", "Escribe memos analíticos y usa software (Atlas.ti, NVivo, MAXQDA) si lo necesitas."],
      ejemplo: "Fragmentos como «me empujaron en la fila» y «se burlan del que pierde» → código «agresión en el juego» → categoría «competencia mal gestionada».",
      error: "Presentar citas de los participantes sin categorizarlas ni interpretarlas.",
      fuente: HS + ", cap. 14" },
    { id: "rigor-cualitativo", cat: "Ruta cualitativa", titulo: "Rigor cualitativo",
      claves: ["rigor", "rigor cualitativo", "credibilidad", "dependencia", "transferencia", "transferibilidad", "confirmabilidad", "confirmacion", "triangulacion", "validez cualitativa"],
      resumen: "La calidad de un estudio cualitativo se valora con criterios propios, equivalentes a la confiabilidad y la validez de lo cuantitativo.",
      puntos: ["Dependencia (consistencia lógica): otros investigadores llegarían a interpretaciones similares con los mismos datos.", "Credibilidad: se captó el significado completo de las experiencias de los participantes.", "Transferencia: el lector puede valorar si los resultados aplican a otro contexto (descripción densa).", "Confirmación: se minimizan los sesgos del investigador (auditoría, reflexividad).", "Estrategias: triangulación de fuentes, investigadores y métodos; chequeo con participantes; bitácora."],
      ejemplo: "«Para la credibilidad se devolvieron las interpretaciones a cinco participantes; para la dependencia, dos investigadores codificaron por separado y se compararon los códigos».",
      error: "Hablar de «validez estadística» en un estudio cualitativo o no decir nada sobre el rigor.",
      fuente: HS + ", cap. 14" },
    { id: "disenos-cualitativos", cat: "Ruta cualitativa", titulo: "Diseños cualitativos",
      claves: ["diseno cualitativo", "disenos cualitativos", "teoria fundamentada", "etnografia", "etnografico", "narrativo", "fenomenologico", "fenomenologia", "investigacion accion", "investigacion-accion", "estudio de caso", "estudio de casos"],
      resumen: "El diseño cualitativo es el abordaje general del estudio; es flexible y se ajusta en el campo. Los básicos son: teoría fundamentada, etnográfico, narrativo, fenomenológico e investigación-acción.",
      puntos: ["Teoría fundamentada: produce una teoría desde los datos (sistemática o emergente).", "Etnográfico: describe y analiza la cultura de un grupo.", "Narrativo: reconstruye historias y experiencias en secuencia.", "Fenomenológico: explora la esencia de una experiencia compartida.", "Investigación-acción: busca resolver un problema práctico con participación de los involucrados (ciclos de diagnóstico, plan, acción y reflexión)."],
      ejemplo: "Un docente que diagnostica la convivencia, diseña con sus estudiantes un programa, lo aplica y reflexiona sobre los cambios hace investigación-acción.",
      error: "Elegir un diseño por su nombre sin seguir sus procedimientos.",
      fuente: HS + ", cap. 15" },
    { id: "reporte-cualitativo", cat: "Ruta cualitativa", titulo: "Reporte cualitativo",
      claves: ["reporte cualitativo", "informe cualitativo", "resultados cualitativos", "escribir resultados cualitativos"],
      resumen: "El reporte cualitativo describe el estudio, el método, las categorías y temas, y su interpretación, con citas de los participantes que ilustran cada categoría. Es más narrativo y flexible que el cuantitativo.",
      puntos: ["Presenta cada categoría con su definición y fragmentos que la sustentan.", "Muestra las relaciones entre categorías (un modelo o un diagrama).", "Discute los hallazgos frente a la literatura.", "Incluye la reflexión del investigador y los criterios de rigor aplicados."],
      ejemplo: "Categoría 1: «Competencia mal gestionada». Definición, tres citas de estudiantes y su interpretación.",
      error: "Convertir el reporte en una lista de citas sin análisis.",
      fuente: HS + ", cap. 16" },

    /* ---------- Ruta mixta ---------- */
    { id: "mixtos", cat: "Ruta mixta", titulo: "Métodos mixtos",
      claves: ["metodos mixtos", "metodo mixto", "enfoque mixto", "investigacion mixta", "diseno mixto", "disenos mixtos", "secuencial", "concurrente", "triangulacion", "anidado", "explicativo secuencial", "exploratorio secuencial", "integracion", "metainferencias"],
      resumen: "Los métodos mixtos recolectan y analizan datos cuantitativos y cualitativos, y los integran para obtener una comprensión más completa del fenómeno. El diseño depende de la prioridad de cada enfoque, la secuencia y el propósito de la integración.",
      puntos: ["Exploratorio secuencial: primero cualitativo, luego cuantitativo (p. ej., para construir un instrumento).", "Explicativo secuencial: primero cuantitativo, luego cualitativo para explicar los resultados.", "De triangulación concurrente: ambos a la vez, para comparar y confirmar.", "Anidado: un enfoque dominante con otro incrustado.", "La integración produce metainferencias: conclusiones que ningún enfoque daría por sí solo."],
      ejemplo: "Fase 1: encuesta de convivencia a 200 estudiantes. Fase 2: entrevistas a 10 con los puntajes más bajos para entender por qué (explicativo secuencial).",
      error: "Llamar «mixto» a un estudio que solo agrega una pregunta abierta a una encuesta, sin integrar los resultados.",
      fuente: HS + ", cap. 17" },

    /* ---------- Ruta teórico-documental ---------- */
    { id: "investigacion-teorica", cat: "Ruta teórico-documental", titulo: "Investigación teórica y documental",
      claves: ["investigacion teorica", "investigacion documental", "enfoque teorico", "teorico documental", "hermeneutica", "hermeneutico", "analisis conceptual", "filosofia", "tesis teorica", "estudio teorico", "revision documental", "investigacion bibliografica", "sin trabajo de campo", "sin participantes"],
      resumen: "Una investigación teórica produce conocimiento a partir de textos, conceptos y argumentos, no de datos de campo. Es la ruta habitual en filosofía, epistemología, teoría educativa, derecho o historia de las ideas. Su rigor depende de cómo se elige el corpus y de cómo se analiza.",
      puntos: ["Diseños: hermenéutico (interpretar textos en su horizonte), análisis conceptual (precisar y reconstruir un concepto), argumentativo o crítico (evaluar tesis y objeciones), genealógico o histórico-conceptual, y revisión sistemática o documental.", "La «muestra» es un corpus: obras, autores, documentos o casos teóricos elegidos con criterios explícitos.", "El instrumento es la ficha o matriz de análisis documental, no un cuestionario.", "No lleva hipótesis estadísticas: se formulan tesis o supuestos que se defienden con argumentos.", "El producto es una tesis argumentada: un modelo, una distinción conceptual o una teoría."],
      ejemplo: "«¿Puede un sistema de lenguaje saber algo?» → análisis conceptual del saber (Gettier, fiabilismo) aplicado a los modelos de lenguaje, sobre un corpus de 40 obras de epistemología e IA.",
      error: "Disfrazar una tesis teórica de cualitativa (con «participantes» y «saturación») o de cuantitativa (con hipótesis y variables) para que parezca más empírica.",
      fuente: "Romus (método Kuetz)" },
    { id: "corpus-documental", cat: "Ruta teórico-documental", titulo: "Corpus y criterios de selección",
      claves: ["corpus", "corpus documental", "seleccion de fuentes", "criterios de inclusion", "criterios de exclusion", "fuentes primarias", "fuentes secundarias", "muestra documental", "muestra teorica"],
      resumen: "En la ruta teórica el corpus reemplaza a la muestra. Debes decir qué textos analizas, por qué esos y no otros, y cómo los encontraste, para que otro investigador pueda reconstruir tu base documental.",
      puntos: ["Distingue fuentes primarias (las obras de los autores que interpretas) de secundarias (comentarios y estudios sobre ellas).", "Declara criterios de inclusión y exclusión: periodo, idioma, tipo de texto, tradición, relevancia para la pregunta.", "Si haces revisión sistemática, documenta bases de datos, cadenas de búsqueda y el flujo de selección (PRISMA).", "El corpus se cierra por suficiencia teórica: cuando nuevas obras ya no cambian el mapa de posiciones."],
      ejemplo: "«Corpus primario: Turing (1950), Searle (1980), Clark y Chalmers (1998). Secundario: 32 artículos de 2015 a 2025 indexados en Scopus y PhilPapers sobre conocimiento y modelos de lenguaje».",
      error: "Citar solo lo que se encontró a mano, sin criterios, o presentar un corpus sesgado hacia una sola posición.",
      fuente: "Romus (método Kuetz)" },
    { id: "analisis-documental", cat: "Ruta teórico-documental", titulo: "Análisis documental y conceptual",
      claves: ["analisis documental", "ficha de analisis", "matriz de analisis", "ficha documental", "fichaje", "analisis de contenido", "reconstruccion argumentativa", "analisis de argumentos", "categorias teoricas", "categorias apriori"],
      resumen: "El análisis documental organiza lo que dicen los textos en categorías teóricas y reconstruye sus argumentos para compararlos y evaluarlos. La ficha de análisis documental es el instrumento que lo hace sistemático.",
      puntos: ["Define categorías a priori desde tu marco teórico y deja abiertas las emergentes.", "En cada ficha registra: referencia, tesis central, conceptos clave, argumento (premisas → conclusión), objeciones y cita textual con página.", "Compara posiciones en una matriz autor × categoría.", "Evalúa los argumentos: validez, supuestos ocultos, contraejemplos.", "Romus puede generar la ficha y la matriz desde tu biblioteca."],
      ejemplo: "Categoría «justificación»: Goldman (1979) la funda en procesos fiables; Lackey (2008) la desplaza al testimonio. ¿Aplica alguna a un modelo de lenguaje?",
      error: "Hacer resúmenes de autores uno tras otro sin categorías ni comparación (el «desfile de autores»).",
      fuente: "Romus (método Kuetz)" },
    { id: "rigor-teorico", cat: "Ruta teórico-documental", titulo: "Rigor en la investigación teórica",
      claves: ["rigor teorico", "validez teorica", "triangulacion teorica", "coherencia argumentativa", "rigor documental", "calidad de una tesis teorica"],
      resumen: "Una tesis teórica es rigurosa si su corpus es trazable, sus conceptos están definidos con precisión y sus argumentos resisten las mejores objeciones.",
      puntos: ["Trazabilidad: cada afirmación remite a una fuente con página.", "Precisión conceptual: define los términos técnicos y no cambies su sentido a mitad del texto.", "Triangulación teórica: contrasta tu interpretación con tradiciones distintas.", "Principio de caridad: reconstruye la mejor versión de la posición que criticas.", "Reflexividad: declara tu posición y sus límites."],
      ejemplo: "«Para evitar el sesgo de confirmación, cada tesis se contrastó con la objeción más fuerte de la tradición opuesta (p. ej., el argumento de la habitación china frente al funcionalismo)».",
      error: "Atacar una versión débil de la posición contraria (falacia del hombre de paja).",
      fuente: "Romus (método Kuetz)" },

    /* ---------- Escritura y normas ---------- */
    { id: "etica", cat: "Escritura y ética", titulo: "Ética en la investigación",
      claves: ["etica", "consentimiento", "consentimiento informado", "asentimiento", "confidencialidad", "comite de etica", "menores", "datos personales", "ley 1581", "habeas data"],
      resumen: "Toda investigación con personas debe proteger su dignidad, su autonomía y su bienestar. Con menores de edad se requiere el consentimiento de los padres y el asentimiento del menor.",
      puntos: ["Consentimiento informado por escrito: objetivo, procedimientos, riesgos, beneficios y derecho a retirarse.", "Confidencialidad y anonimato en el reporte.", "En Colombia, el tratamiento de datos personales se rige por la Ley 1581 de 2012.", "Solicita el aval del comité de ética de tu institución cuando aplique."],
      ejemplo: "«Los datos se codificarán con números; ningún nombre aparecerá en el informe».",
      error: "Recolectar datos de estudiantes sin autorización de los acudientes ni de la institución.",
      fuente: HS + " (centro de recursos en línea: ética en la investigación); Ley 1581 de 2012" },
    { id: "apa", cat: "Escritura y ética", titulo: "Citas y referencias en APA 7",
      claves: ["apa", "apa 7", "normas apa", "citas", "citar", "referencias", "bibliografia", "como citar", "cita textual", "parafraseo", "et al"],
      resumen: "APA 7 usa el sistema autor-año. Toda cita en el texto debe tener su referencia en la lista final, y viceversa. Romus puede buscar fuentes reales y citarlas automáticamente.",
      puntos: ["Parafraseo: (Apellido, año). Cita textual corta: entre comillas con página (Apellido, año, p. 23).", "Dos autores: (Pérez y Gómez, 2021). Tres o más: (Pérez et al., 2021).", "Cita textual de 40 palabras o más: en bloque aparte, sin comillas, con sangría.", "Referencias en orden alfabético, con sangría francesa y DOI cuando exista."],
      ejemplo: "Gómez Rojas, M. F., Pérez, L. y Ruiz Díaz, A. (2021). Juegos cooperativos y convivencia escolar. Revista de Educación Física, 12(3), 45-60. https://doi.org/…",
      error: "Poner en la lista de referencias obras que no se citan en el texto, o citar sin referencia.",
      fuente: "Manual de publicaciones APA, 7.ª ed.", accion: "literatura" },
    { id: "uso-ia", cat: "Escritura y ética", titulo: "Uso responsable de la IA en tu proyecto",
      claves: ["inteligencia artificial", "ia", "uso de ia", "declaracion de uso de ia", "plagio", "integridad academica", "chatgpt"],
      resumen: "La IA puede orientar, revisar y sugerir, pero la autoría, las decisiones metodológicas y la responsabilidad son del investigador. Muchas instituciones piden declarar cómo se usó.",
      puntos: ["Verifica todo lo que proponga la IA: puede equivocarse o inventar datos.", "Nunca uses referencias que no hayas comprobado (Romus solo cita fuentes reales de OpenAlex).", "Reescribe con tu voz lo que la IA sugiera.", "Declara el uso: di «declaración de uso de IA» y Romus la agrega con el registro."],
      ejemplo: "«Se usó Romus con el modelo X para revisar la coherencia y buscar literatura; las decisiones y la redacción final son del autor».",
      error: "Entregar texto generado por IA como propio sin revisarlo ni declararlo.",
      fuente: "Romus", accion: "declaracion" },
    /* ---------- Biblioteca: temas de profundización (texto original de Romus) ---------- */
    { id: "antecedentes", cat: "Marco teórico", titulo: "Antecedentes y estado del arte",
      claves: ["antecedentes", "estado del arte", "estado de la cuestion", "investigaciones previas", "estudios previos", "matriz de antecedentes"],
      resumen: "Los antecedentes son los estudios que ya abordaron tu problema o uno cercano. Con ellos muestras qué se sabe, cómo se ha estudiado y qué falta. El estado del arte los organiza y los pone a dialogar para revelar el vacío que tu trabajo va a llenar.",
      pasos: ["Busca en bases académicas con palabras clave en español y en inglés.", "Selecciona por pertinencia, calidad y actualidad (por lo general, los últimos 5 a 10 años, más los clásicos).", "Registra en una matriz: autor, año, país, objetivo, método, muestra, hallazgos y limitaciones.", "Agrupa los estudios por temas o enfoques, no uno por uno.", "Cierra con lo que falta: un contexto, una población, un método o una pregunta que nadie ha respondido."],
      puntos: ["Lo internacional, lo nacional y lo local ayudan a ubicar tu aporte.", "Cada antecedente se cita y se relaciona con tu estudio: ¿en qué se parece y en qué se diferencia?", "El vacío del conocimiento justifica tu investigación."],
      ejemplo: "«Los estudios revisados (n = 18) evalúan programas de juego cooperativo en primaria; ninguno lo hace en secundaria pública colombiana ni mide la convivencia en el recreo».",
      error: "Hacer una lista de resúmenes sin compararlos ni sacar conclusiones.",
      fuente: HS + ", cap. 4", accion: "literatura" },
    { id: "marco-conceptual", cat: "Marco teórico", titulo: "Marco conceptual: definir los términos clave",
      claves: ["marco conceptual", "conceptos", "definiciones", "glosario", "definir conceptos", "categorias teoricas"],
      resumen: "El marco conceptual define con precisión los conceptos centrales de tu estudio y explica cómo se relacionan. Una buena definición se apoya en autores, se ajusta a tu contexto y no deja dudas sobre qué vas a estudiar.",
      puntos: ["Define solo los conceptos que de verdad usas en tu pregunta y tus objetivos.", "Contrasta dos o tres definiciones y elige (o construye) la que asumirás.", "Explica las relaciones entre conceptos: un esquema ayuda mucho.", "En la ruta cuantitativa, cada concepto clave se convierte después en variable; en la cualitativa, en categoría inicial."],
      ejemplo: "«En este estudio, convivencia escolar se entiende como la calidad de las relaciones entre estudiantes en los espacios comunes, observable en la frecuencia de conflictos y en la forma de resolverlos».",
      error: "Copiar definiciones de diccionario o acumular conceptos que nunca vuelven a aparecer.",
      fuente: HS + ", caps. 4 y 6" },
    { id: "niveles-medicion", cat: "Ruta cuantitativa", titulo: "Niveles de medición",
      claves: ["niveles de medicion", "nivel de medicion", "escala de medicion", "nominal", "ordinal", "intervalo", "razon", "tipo de variable", "variable categorica", "variable continua"],
      resumen: "Cada variable se mide en un nivel, y ese nivel decide qué estadística puedes usar. Hay cuatro niveles, de menor a mayor información: nominal, ordinal, de intervalo y de razón.",
      tipos: ["Nominal: categorías sin orden (sexo, colegio, deporte favorito).", "Ordinal: categorías con orden pero sin distancias iguales (nivel socioeconómico, escalas «nunca–a veces–siempre»).", "Intervalo: distancias iguales sin cero absoluto (temperatura en °C, puntajes de muchas escalas).", "Razón: distancias iguales y cero real (edad, peso, número de conflictos)."],
      puntos: ["Con datos nominales se usan frecuencias y chi cuadrado.", "Con ordinales, medianas y pruebas no paramétricas.", "Con intervalo y razón, medias, desviaciones y pruebas paramétricas si se cumplen los supuestos.", "Decide el nivel antes de redactar el instrumento: después es difícil cambiarlo."],
      ejemplo: "Preguntar «¿cuántas veces discutiste esta semana?» (razón) da más información que «¿discutes poco o mucho?» (ordinal).",
      error: "Calcular el promedio de una variable nominal, como el «promedio del colegio».",
      fuente: HS + ", cap. 9" },
    { id: "cuestionario", cat: "Ruta cuantitativa", titulo: "Cuestionarios y escalas de actitud",
      claves: ["cuestionario", "encuesta", "preguntas cerradas", "preguntas abiertas", "escala likert", "likert", "diferencial semantico", "redactar preguntas", "items"],
      resumen: "El cuestionario es un conjunto de preguntas sobre las variables que vas a medir. Las preguntas cerradas facilitan el análisis; las abiertas recogen matices. Las escalas de actitud, como la de Likert, miden la intensidad de una opinión con afirmaciones y opciones graduadas.",
      pasos: ["Parte de la operacionalización: cada indicador da origen a uno o más ítems.", "Redacta ítems claros, breves y con una sola idea cada uno.", "Usa un lenguaje adecuado a los participantes (edad, nivel educativo, cultura).", "Ordena: primero lo general y fácil; al final, los datos personales.", "Somételo a jueces expertos y a una prueba piloto antes de aplicarlo."],
      puntos: ["Likert: afirmaciones con cinco o siete opciones, de «totalmente en desacuerdo» a «totalmente de acuerdo».", "Mezcla afirmaciones positivas y negativas para evitar respuestas automáticas.", "Evita preguntas que sugieren la respuesta, dobles o con negaciones dobles."],
      ejemplo: "Ítem bueno: «En el recreo, mis compañeros me incluyen en sus juegos». Ítem malo: «¿No crees que el recreo es aburrido y violento?».",
      error: "Inventar el cuestionario sin relación con las variables ni con los objetivos.",
      fuente: HS + ", cap. 9", accion: "instrumento" },
    { id: "tipos-muestreo", cat: "Ruta cuantitativa", titulo: "Tipos de muestreo, paso a paso",
      claves: ["tipos de muestreo", "muestreo aleatorio simple", "muestreo estratificado", "muestreo por racimos", "muestreo sistematico", "muestreo por conveniencia", "bola de nieve", "muestreo intencional"],
      resumen: "El tipo de muestreo depende de si quieres generalizar a la población. Si sí, necesitas un muestreo probabilístico, en el que todos tienen la misma oportunidad de ser elegidos; si no, uno no probabilístico, que se justifica por las características del estudio.",
      tipos: ["Aleatorio simple: sorteo sobre la lista completa.", "Sistemático: se elige uno de cada k casos a partir de un inicio al azar.", "Estratificado: se divide la población en grupos (por ejemplo, grados) y se sortea en cada uno, en proporción a su tamaño.", "Por racimos o conglomerados: se sortean grupos completos (por ejemplo, cursos) cuando no hay lista de individuos.", "No probabilísticos: por conveniencia, por cuotas, de casos tipo o en cadena (bola de nieve)."],
      puntos: ["Calcula primero el tamaño y luego aplica el procedimiento de selección.", "Describe el procedimiento con tanto detalle que otra persona pueda repetirlo.", "Prevé pérdidas: suma entre 10 % y 15 % por si algunos no responden."],
      ejemplo: "Se necesitan 214 estudiantes de 480. Sexto tiene 120 (25 %), así que se sortean 54 de sexto, y así con cada grado.",
      error: "Decir «muestreo aleatorio» cuando se aplicó la encuesta a quienes estaban disponibles.",
      fuente: HS + ", cap. 8", accion: "muestra" },
    { id: "validez-experimental", cat: "Ruta cuantitativa", titulo: "Validez interna y externa en experimentos",
      claves: ["validez interna", "validez externa", "amenazas a la validez", "grupo control", "grupo experimental", "fuentes de invalidacion", "cuasiexperimento", "preprueba", "posprueba"],
      resumen: "Un experimento tiene validez interna cuando los cambios observados se deben de verdad al tratamiento y no a otras causas. Tiene validez externa cuando los resultados pueden extenderse a otras personas, lugares o momentos.",
      puntos: ["Amenazas internas frecuentes: sucesos externos durante el estudio, maduración natural de los participantes, efecto de la preprueba, cambios en el instrumento, abandono de participantes y grupos que no eran equivalentes.", "Se controlan con grupo de comparación, asignación al azar, preprueba y posprueba, y aplicando el tratamiento igual para todos.", "En la escuela suelen usarse cuasiexperimentos (grupos ya formados): reconoce esa limitación.", "La validez externa mejora con muestras diversas y situaciones parecidas a la vida real."],
      ejemplo: "Si un programa de juego cooperativo coincide con una campaña institucional contra el acoso, la mejora puede deberse a la campaña: un grupo control ayuda a separar los efectos.",
      error: "Atribuir todo el cambio al programa sin grupo de comparación.",
      fuente: HS + ", cap. 7" },
    { id: "estadistica-descriptiva", cat: "Ruta cuantitativa", titulo: "Estadística descriptiva",
      claves: ["estadistica descriptiva", "media", "mediana", "moda", "desviacion estandar", "frecuencias", "porcentajes", "tablas de frecuencia", "graficos"],
      resumen: "La estadística descriptiva resume cómo se comportan los datos de cada variable: cuántos hay en cada categoría, cuál es el valor típico y qué tanto se dispersan. Siempre va antes de probar hipótesis.",
      puntos: ["Frecuencias y porcentajes para variables nominales y ordinales.", "Tendencia central: media (promedio), mediana (valor del centro) y moda (el más repetido).", "Dispersión: rango y desviación estándar (qué tanto se alejan los datos de la media).", "Forma de la distribución: asimetría y curtosis, útiles para decidir entre pruebas paramétricas y no paramétricas.", "Una tabla o un gráfico bien titulado vale más que un párrafo de números."],
      ejemplo: "«El número de conflictos semanales en el recreo tuvo una media de 4,2 (DE = 1,8) y una mediana de 4».",
      error: "Usar la media cuando hay valores extremos: la mediana representa mejor esos datos.",
      fuente: HS + ", cap. 10", accion: "spss" },
    { id: "estadistica-inferencial", cat: "Ruta cuantitativa", titulo: "Pruebas de hipótesis: cuál usar",
      claves: ["estadistica inferencial", "prueba de hipotesis", "que prueba uso", "valor p", "significancia", "t de student", "anova", "pearson", "spearman", "chi cuadrado", "mann whitney", "wilcoxon", "tamano del efecto"],
      resumen: "La estadística inferencial usa los datos de la muestra para sacar conclusiones sobre la población. La prueba adecuada depende de tu hipótesis (diferencia o relación), del número de grupos, de si los grupos son independientes o relacionados y del nivel de medición.",
      tipos: ["Comparar dos grupos independientes: t de Student o U de Mann-Whitney.", "Comparar el mismo grupo antes y después: t para muestras relacionadas o Wilcoxon.", "Comparar tres o más grupos: ANOVA o Kruskal-Wallis.", "Relacionar dos variables numéricas: correlación de Pearson o de Spearman.", "Relacionar dos variables categóricas: chi cuadrado."],
      puntos: ["Si p < 0,05, se rechaza la hipótesis nula con un 95 % de confianza.", "Que una diferencia sea significativa no quiere decir que sea grande: informa el tamaño del efecto.", "Revisa los supuestos (normalidad, homogeneidad de varianzas) antes de elegir una prueba paramétrica."],
      ejemplo: "«Hubo menos conflictos después del programa, t(29) = 3,41, p = 0,002, d = 0,62».",
      error: "Usar la misma prueba para todo o reportar solo «fue significativo» sin los valores.",
      fuente: HS + ", cap. 10", accion: "spss" },
    { id: "entrevista", cat: "Ruta cualitativa", titulo: "Cómo hacer una buena entrevista",
      claves: ["entrevista", "entrevistas", "guion de entrevista", "entrevista semiestructurada", "entrevista a profundidad", "preguntas de entrevista", "entrevistar"],
      resumen: "La entrevista cualitativa es una conversación con propósito para comprender la experiencia del otro con sus propias palabras. Puede ser estructurada, semiestructurada (la más usada en tesis) o abierta.",
      pasos: ["Prepara un guion con preguntas abiertas, derivadas de tus categorías iniciales.", "Empieza con preguntas generales y fáciles; deja las sensibles para cuando haya confianza.", "Escucha más de lo que hablas; pide ejemplos: «cuéntame una vez en que…».", "Graba con consentimiento y toma notas de lo que no queda en el audio.", "Transcribe pronto y anota tus primeras impresiones."],
      puntos: ["Las preguntas deben ser neutrales: no sugieras la respuesta.", "Usa preguntas de profundización: «¿qué quieres decir con…?», «¿y cómo te sentiste?».", "Agradece y explica qué pasará con la información."],
      ejemplo: "En lugar de «¿el recreo es violento?», pregunta «¿cómo es un recreo normal para ti?».",
      error: "Convertir la entrevista en un cuestionario oral con preguntas de sí o no.",
      fuente: HS + ", cap. 14", accion: "instrumento" },
    { id: "observacion", cat: "Ruta cualitativa", titulo: "Observación cualitativa y diario de campo",
      claves: ["observacion", "observacion participante", "diario de campo", "notas de campo", "bitacora", "observar"],
      resumen: "Observar en investigación cualitativa no es solo mirar: es estar atento a detalles, situaciones e interacciones, y registrarlas de forma sistemática. El investigador puede observar desde fuera o participar en la actividad.",
      puntos: ["Define qué observarás (espacios, interacciones, rutinas) sin cerrarte a lo inesperado.", "Separa en tus notas lo que viste (descripción) de lo que piensas (interpretación).", "Registra fecha, hora, lugar y participantes en cada entrada.", "Anota tus propias reacciones: también son datos sobre el proceso."],
      ejemplo: "Descripción: «10:05, cancha: cuatro estudiantes de 6.º excluyen a uno del partido». Interpretación: «parece que la habilidad deportiva decide quién juega».",
      error: "Escribir solo opiniones («el recreo es un caos») sin describir los hechos.",
      fuente: HS + ", cap. 14" },
    { id: "triangulacion", cat: "Ruta cualitativa", titulo: "Triangulación",
      claves: ["triangulacion", "triangular", "triangulacion de datos", "triangulacion de fuentes", "triangulacion de metodos", "contrastar fuentes"],
      resumen: "Triangular es mirar el mismo fenómeno desde varios ángulos para que las conclusiones no dependan de una sola fuente. Le da solidez y credibilidad a la investigación.",
      tipos: ["De fuentes: estudiantes, docentes y familias.", "De métodos: entrevista, observación y documentos.", "De investigadores: dos personas codifican y comparan.", "De teorías: interpretar los datos desde perspectivas distintas."],
      puntos: ["Muestra dónde coinciden las fuentes y también dónde se contradicen.", "Las contradicciones no son un fracaso: suelen ser hallazgos.", "En los métodos mixtos, triangular es una forma de integrar."],
      ejemplo: "Los estudiantes dicen que «no hay peleas», pero el diario de campo registra empujones diarios: esa diferencia es un hallazgo sobre cómo se normaliza la violencia.",
      error: "Llamar «triangulación» a citar tres autores que dicen lo mismo.",
      fuente: HS + ", caps. 14 y 17", accion: "discusion" },
    { id: "teoria-fundamentada", cat: "Ruta cualitativa", titulo: "Teoría fundamentada",
      claves: ["teoria fundamentada", "grounded theory", "codificacion abierta", "codificacion axial", "codificacion selectiva", "categoria central", "muestreo teorico"],
      resumen: "La teoría fundamentada construye una explicación (una teoría) a partir de los datos, en lugar de partir de una teoría previa. Se usa cuando no hay explicaciones satisfactorias del fenómeno en tu contexto.",
      pasos: ["Codificación abierta: lee línea por línea y nombra unidades de significado.", "Codificación axial: agrupa los códigos en categorías y relaciónalas (causas, condiciones, acciones, consecuencias).", "Codificación selectiva: identifica la categoría central que integra todo.", "Muestreo teórico: busca nuevos casos para completar las categorías hasta la saturación.", "Escribe memos durante todo el proceso."],
      puntos: ["Hay una versión sistemática (con un esquema fijo) y otra emergente (más abierta).", "El producto es un modelo o una teoría sustantiva, aplicable al contexto estudiado."],
      ejemplo: "A partir de entrevistas surge la categoría central «jugar para pertenecer», que explica por qué los conflictos aparecen al formar los equipos.",
      error: "Decir que se hizo teoría fundamentada y entregar solo una lista de categorías sin teoría.",
      fuente: HS + ", cap. 15", accion: "atlas" },
    { id: "etnografia", cat: "Ruta cualitativa", titulo: "Diseño etnográfico",
      claves: ["etnografia", "etnografico", "cultura", "trabajo de campo", "inmersion", "comunidad"],
      resumen: "La etnografía describe e interpreta la cultura de un grupo: sus creencias, prácticas, normas y significados compartidos. Exige una inmersión prolongada en el contexto.",
      puntos: ["Combina observación participante, entrevistas y documentos.", "Busca comprender «desde dentro» cómo el grupo ve su mundo.", "El diario de campo es la herramienta central.", "El reporte describe con detalle (descripción densa) y explica los patrones culturales."],
      ejemplo: "Estudiar durante un semestre las reglas no escritas del recreo: quién juega dónde, quién decide y cómo se castiga a quien rompe las normas.",
      error: "Llamar etnografía a dos visitas cortas al lugar.",
      fuente: HS + ", cap. 15" },
    { id: "fenomenologia", cat: "Ruta cualitativa", titulo: "Diseño fenomenológico",
      claves: ["fenomenologia", "fenomenologico", "experiencia vivida", "vivencia", "esencia de la experiencia"],
      resumen: "El diseño fenomenológico explora cómo viven las personas una experiencia común y qué significa para ellas. Busca los elementos esenciales que comparten esas vivencias.",
      pasos: ["Elige participantes que hayan vivido la experiencia.", "Recoge descripciones detalladas, sobre todo con entrevistas a profundidad.", "Identifica unidades de significado y agrúpalas en temas.", "Describe la experiencia: qué se vivió y cómo se vivió.", "Reconoce y deja a un lado tus propias ideas previas mientras analizas."],
      puntos: ["La pregunta típica es «¿cómo es vivir…?» o «¿qué significa…?».", "Con pocos participantes y mucha profundidad es suficiente."],
      ejemplo: "«¿Cómo viven los estudiantes la experiencia de ser excluidos del juego en el recreo?».",
      error: "Hacer preguntas de causa-efecto («¿qué factores causan…?»), que corresponden a otros diseños.",
      fuente: HS + ", cap. 15" },
    { id: "narrativo", cat: "Ruta cualitativa", titulo: "Diseño narrativo",
      claves: ["narrativo", "diseno narrativo", "historias de vida", "biografico", "relatos", "autobiografia"],
      resumen: "El diseño narrativo reconstruye las historias de las personas para entender sus experiencias y los sucesos que las marcaron, en orden cronológico y dentro de su contexto.",
      puntos: ["Fuentes: entrevistas, cartas, diarios, fotografías y documentos.", "Se organiza la historia en secuencia: antes, punto de quiebre, después.", "El investigador interpreta los relatos, no solo los transcribe.", "Puede centrarse en una persona, en un grupo o en un suceso."],
      ejemplo: "Reconstruir la trayectoria de tres docentes de educación física desde su formación hasta su manera actual de enseñar.",
      error: "Confundirlo con una biografía periodística, sin análisis.",
      fuente: HS + ", cap. 15" },
    { id: "investigacion-accion", cat: "Ruta cualitativa", titulo: "Investigación-acción",
      claves: ["investigacion accion", "investigacion-accion", "iap", "investigacion accion participativa", "ciclos", "intervencion", "transformar la practica"],
      resumen: "La investigación-acción busca comprender y resolver un problema concreto de una comunidad o institución, con la participación de las personas implicadas. Une la investigación con el cambio de la práctica.",
      pasos: ["Diagnóstico: detectar y entender el problema con los participantes.", "Plan: diseñar juntos una acción para transformarlo.", "Acción: aplicar el plan y recoger información mientras ocurre.", "Reflexión: evaluar qué cambió y por qué.", "Nuevo ciclo: ajustar el plan y repetir."],
      puntos: ["Es muy usada por docentes que investigan su propia aula.", "La versión participativa da a la comunidad un papel protagónico en todo el proceso.", "Documenta cada ciclo con evidencias."],
      ejemplo: "El docente y sus estudiantes crean acuerdos de juego para el recreo, los aplican un mes, revisan los conflictos y reformulan los acuerdos.",
      error: "Aplicar una intervención sin diagnóstico ni reflexión y llamarla investigación-acción.",
      fuente: HS + ", cap. 15" },
    { id: "discusion", cat: "Escritura y ética", titulo: "Discusión y conclusiones",
      claves: ["discusion", "discusion de resultados", "conclusiones", "recomendaciones", "limitaciones", "implicaciones"],
      resumen: "La discusión interpreta los resultados: qué significan, cómo se relacionan con los antecedentes y la teoría, y qué limitaciones tienen. Las conclusiones responden de forma directa la pregunta y los objetivos.",
      pasos: ["Resume el hallazgo principal en una o dos frases.", "Compáralo con los antecedentes: ¿coincide o contradice? ¿Por qué?", "Explica los resultados inesperados.", "Reconoce las limitaciones del estudio.", "Señala las implicaciones prácticas y las nuevas preguntas."],
      puntos: ["Las conclusiones van una por objetivo, en el mismo orden.", "No introduzcas datos nuevos en la discusión.", "Las recomendaciones deben salir de los resultados, no de lo que pensabas antes de investigar."],
      ejemplo: "«Al igual que en el estudio de Ruiz (2021), el juego cooperativo redujo los conflictos; sin embargo, aquí el efecto fue menor en los varones, posiblemente por…».",
      error: "Repetir los resultados con otras palabras sin interpretarlos.",
      fuente: HS + ", cap. 11", accion: "discusion" },
    { id: "resumen-abstract", cat: "Escritura y ética", titulo: "Resumen y abstract",
      claves: ["resumen", "abstract", "palabras clave", "keywords", "como hacer el resumen"],
      resumen: "El resumen presenta todo el estudio en un solo párrafo: problema, objetivo, método, resultados principales y conclusión. Muchos lectores solo leen esa parte, así que debe entenderse por sí sola.",
      puntos: ["Extensión habitual: entre 150 y 250 palabras (revisa la norma de tu universidad).", "Escríbelo al final, cuando el trabajo esté terminado.", "Incluye datos concretos: participantes, diseño y resultados con cifras.", "Agrega de tres a cinco palabras clave, idealmente de un tesauro.", "El abstract es la traducción fiel al inglés."],
      ejemplo: "«Este estudio cuasiexperimental evaluó el efecto de un programa de juego cooperativo en la convivencia de 60 estudiantes de sexto grado…».",
      error: "Escribir una introducción general en lugar de resumir los resultados.",
      fuente: HS + ", cap. 11", accion: "resumen" },
    { id: "proyecto", cat: "Planteamiento", titulo: "El proyecto o propuesta de investigación",
      claves: ["proyecto de investigacion", "propuesta de investigacion", "anteproyecto", "protocolo", "partes del proyecto", "estructura del proyecto"],
      resumen: "El proyecto es el plan de la investigación antes de hacerla: qué vas a estudiar, por qué, cómo y con qué recursos. Sirve para que el asesor o el comité lo aprueben y para guiarte después.",
      partes: ["Título", "Planteamiento del problema, pregunta y objetivos", "Justificación y viabilidad", "Marco teórico y antecedentes", "Hipótesis o supuestos (si aplica)", "Metodología: enfoque, diseño, participantes, instrumentos, procedimiento, análisis y ética", "Cronograma y presupuesto", "Referencias"],
      puntos: ["Todo debe ser coherente: la pregunta, los objetivos y el método se corresponden.", "En el proyecto se escribe en futuro («se aplicará»); en el informe final, en pasado.", "Revisa la plantilla de tu institución: los nombres de las partes cambian."],
      ejemplo: "La matriz de coherencia de Romus muestra en una tabla si cada objetivo tiene su instrumento y su análisis.",
      error: "Diseñar el método sin mirar los objetivos, o prometer más de lo que se puede hacer en el tiempo disponible.",
      fuente: "Romus (método Kuetz)", accion: "coherencia" }
  ];

  /* ---------- Rutas del modo tutorial (orden del proceso) ---------- */
  const RUTAS = {
    cuantitativo: ["investigacion", "enfoques", "idea", "proyecto", "planteamiento", "objetivos", "preguntas", "justificacion", "viabilidad", "marco-teorico", "revision-literatura", "antecedentes", "marco-conceptual", "alcance", "hipotesis", "variables", "niveles-medicion", "diseno-experimental", "validez-experimental", "diseno-no-experimental", "muestra", "tipos-muestreo", "instrumentos", "cuestionario", "analisis-cuantitativo", "estadistica-descriptiva", "estadistica-inferencial", "etica", "reporte-cuantitativo", "discusion", "resumen-abstract", "apa", "uso-ia"],
    cualitativo: ["investigacion", "enfoques", "epistemologia", "idea", "proyecto", "planteamiento-cualitativo", "preguntas", "justificacion", "viabilidad", "marco-teorico", "revision-literatura", "antecedentes", "marco-conceptual", "disenos-cualitativos", "teoria-fundamentada", "etnografia", "fenomenologia", "narrativo", "investigacion-accion", "muestreo-cualitativo", "recoleccion-cualitativa", "entrevista", "observacion", "analisis-cualitativo", "triangulacion", "rigor-cualitativo", "etica", "reporte-cualitativo", "discusion", "resumen-abstract", "cientificidad", "apa", "uso-ia"],
    teorico: ["investigacion", "enfoques", "epistemologia", "investigacion-teorica", "idea", "proyecto", "planteamiento", "preguntas", "objetivos", "justificacion", "viabilidad", "marco-teorico", "revision-literatura", "antecedentes", "marco-conceptual", "corpus-documental", "analisis-documental", "rigor-teorico", "discusion", "resumen-abstract", "apa", "uso-ia"],
    mixto: ["investigacion", "enfoques", "epistemologia", "idea", "proyecto", "planteamiento", "objetivos", "preguntas", "justificacion", "marco-teorico", "revision-literatura", "antecedentes", "marco-conceptual", "mixtos", "muestra", "tipos-muestreo", "muestreo-cualitativo", "instrumentos", "cuestionario", "recoleccion-cualitativa", "entrevista", "analisis-cuantitativo", "estadistica-descriptiva", "estadistica-inferencial", "analisis-cualitativo", "triangulacion", "rigor-cualitativo", "etica", "discusion", "resumen-abstract", "apa", "uso-ia"]
  };


  /* ---------- Búsqueda ---------- */
  const norm = (t) => String(t || "").toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[^a-z0-9ñ ]+/g, " ").replace(/\s+/g, " ").trim();
  const VACIAS = new Set("que es son como se hace hago una uno unos unas el la los las de del al en y o a para por con sin sobre mi mis tu su sus me te lo le les esto este esta eso cual cuales cuando donde quien explica explicame dime ayuda ayudame guia tutorial significa significan sirve hacer hacerlo redacto redactar formulo formular escribo escribir elijo elegir defino definir calculo calcular diferencia entre tipos tipo romus ok porfa favor por favor quiero saber necesito".split(" "));
  const indexar = (t) => ({ t, frases: [norm(t.titulo)].concat(t.claves.map(norm)), texto: " " + norm([t.titulo, t.claves.join(" "), t.resumen, t.puntos.join(" "), (t.tipos || []).join(" ")].join(" ")) + " " });
  let INDICE = TEMAS.map(indexar);
  /** Agrega temas de otra biblioteca (por ejemplo, la Teoría de Brian Suárez). */
  function agregar(temas) { temas.forEach(t => { if (!TEMAS.some(x => x.id === t.id)) { TEMAS.push(t); INDICE.push(indexar(t)); } }); }
  const raiz = (w) => w.length > 6 ? w.slice(0, w.length - 2) : w;

  /** Devuelve [{t, puntos}] ordenados por relevancia. */
  function buscar(consulta, max) {
    const q = " " + norm(consulta) + " ";
    const palabras = norm(consulta).split(" ").filter(w => w.length >= 3 && !VACIAS.has(w));
    if (!palabras.length) return [];
    return INDICE.map(({ t, frases, texto }) => {
      let p = 0;
      frases.forEach(f => { if (f.length > 3 && q.includes(" " + f + " ")) p += 3 + f.split(" ").length; });
      palabras.forEach(w => {
        const r = raiz(w);
        if (frases.some(f => (" " + f + " ").includes(" " + r))) p += 2;
        else if (texto.includes(" " + r)) p += 0.5;
      });
      return { t, puntos: p };
    }).filter(x => x.puntos >= 2).sort((a, b) => b.puntos - a.puntos).slice(0, max || 3);
  }

  function tema(id) { return TEMAS.find(t => t.id === id); }
  function categorias() { const c = []; TEMAS.forEach(t => { if (!c.includes(t.cat)) c.push(t.cat); }); return c; }

  /** Texto plano de un tema (para la IA o para leer en voz alta). */
  function textoPlano(t) {
    const lista = (nombre, xs) => xs && xs.length ? `\n${nombre}:\n- ${xs.join("\n- ")}` : "";
    return `${t.titulo}\n${t.resumen}${lista("Puntos clave", t.puntos)}${lista("Tipos", t.tipos)}${lista("Cómo se construye", t.pasos)}${lista("Partes", t.partes)}${lista("Ejemplos por nivel", t.niveles)}` +
      (t.ejemplo ? `\nEjemplo: ${t.ejemplo}` : "") + (t.error ? `\nError frecuente: ${t.error}` : "") + `\nFuente: ${t.fuente}`;
  }

  return { TEMAS, RUTAS, buscar, tema, categorias, textoPlano, norm, agregar };
})();
